### PR TITLE
fix: update windows for new changes

### LINKED ISSUE #37: Make v1 available on Window
Perform needed changes on windows.rs to release v1 on it.

Update release action:
https://github.com/jkfran/killport/blob/4997258c1f75825593ed640ca6d71a9852b5125d/.github/workflows/release.yml#L67

### PR DESCRIPTION
**Pull request by jacobtread**
Looks like a fair bit of unix-specific code has gotten tangled up in the main files

**Description of the changes**

Updated windows support for the latest changes that came in on the unix side of things

- Have separated the unix specific process logic into the unix.rs module
- Created a wrapper for the Signal type since its not available on non unix platforms, non unix platforms just handle it as a uppercase string (No special handling at this stage, but could be implemented at a later stage if we make our own signal enum that maps to the unix enum)
- Added a new WindowsProcess type for windows processes,
- Wired up the code to collect and kill in separate places
- Added process name lookup for windows processes (To match the other impls) if a process has a bad name or fails to obtain its name None is used instead
- Docker container killing is working
- Made the type for a killable into an enum as its possible values are constant?
- Renamed the killport_tests.rs to killport_unix_tests.rs and gated it to unix only since its using unix specific features, Windows tests will need to be added
- Added a build and release target for windows to the github workflows
- Added windows tests
- Updated integration tests to handle windows process names

**Related issue(s)**
If this PR is related to an existing issue, please link to it using the `Fixes #issue_number` or `Closes #issue_number` syntax.

- Closes #37 

**Type of change**
Please select one or multiple of the following options:
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code cleanup (refactoring or improving code quality)
- [ ] Documentation update (adding or updating documentation, updating README)

**Checklist:**
- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

**Additional information**
Add any other information or screenshots about the pull request here.

### CODE REVIEW

**Comment by jacobtread** [comment]
I have noticed a flaw in the previous algorithm I used for resolving the parent processes, it would only manage to catch some of the parents since it only did a single pass over the collection of processes (So it would only pick up the one parent or maybe more if they were in the entries after) 

I implemented a proper version that catches all the processes and I've realized very quickly that we don't want to be killing all the parent processes. (Long story short it ends up killing explorer.exe and winlogon.exe)

So I've limited it to only resolving 1 parent using a constant named MAX_PARENT_DEPTH for choosing how deep to resolve the parents. We might want to gate killing the parent processes behind a optional argument, that provides the max depth?

File: src/killport.rs [hunk 1]
```diff
@@ -133,9 +101,10 @@ impl KillportOperations for Killport {
 
             for process in target_processes {
                 // Check if the process name contains 'docker' and skip if in docker mode
-                if docker_present && process.name.to_lowercase().contains("docker") {
+                if docker_present && process.get_name().to_lowercase().contains("docker") {
```
Comment (jkfran) [inline src/killport.rs:104]: > Docker container killing is working, however it doesn't work properly if you don't explicitly specify the container mode (I think its trying to kill the wrong one causing it to fail?)

I think it is probably because it is killing the Docker process? This conditional here avoids killing the docker process if it is on "auto" mode.

**Comment by jkfran** [comment]
Thank you so much for this.

> So I've limited it to only resolving 1 parent using a constant named MAX_PARENT_DEPTH for choosing how deep to resolve the parents. We might want to gate killing the parent processes behind a optional argument, that provides the max depth?

Killing the parents is missing on Linux and Macos as well. This could be an optional argument we could add into it in the future. Feel free to not kill parents at the moment. One question what happens if the process doesn't have any parents and MAX_PARENT_DEPTH=1 will it kill explorer.exe or winlogon.exe?

**Comment by jacobtread** [comment]
Yeah, you're right. If theres no other parents, it'd still kill Explorer, I think we had this behavior because of a nginx process that would auto restart itself. I will disable this tonight for now. I will leave the code around for resolving parents just in case we want it later

File: src/killport.rs (hunk 1 above)
Comment (jacobtread) [reply src/killport.rs:104]: I'm pretty sure the strange behavior I was seeing here was due to the parent killing behavior, I believe it was trying to go up the tree and kill the parents of the container like WSL (Because they didn't meet the matching name)

Fixed this when I merged the parents onto the processes rather than in the list to kill, so not an issue anymore

**Comment by jacobtread** [comment]
I have set the MAX_PARENT_DEPTH const to zero for now so it won't kill any parents :)

Should be all good to go!

**Review by jkfran — APPROVED** [review]
